world_size: 1
gpu_ranks: 0

data: data/data
save_model: runs/second/model
keep_checkpoint: 10

# pickle error on torch.load()
pre_word_vecs_enc: data/embeddings.enc.pt
pre_word_vecs_dec: data/embeddings.dec.pt

word_vec_size: 200
layers: 3
bridge: True

optim: adam
learning_rate: 0.001

train_steps: 100000
valid_steps: 10000

report_every: 1000
log_file: runs/second/log.txt
tensorboard: True
tensorboard_log_dir: runs/second

