src: data/europarl-v7/europarl-v7.fr-en.en.val 
tgt: data/europarl-v7/europarl-v7.fr-en.fr.val
# src: src.txt
# tgt: tgt.txt
model: runs/second/model_step_90000.pt
report_bleu: True
report_rouge: True
