world_size: 1
gpu_ranks: 0

data: data/data
save_model: models/model
keep_checkpoint: 10

# pickle error on torch.load()
# pre_word_vecs_enc: glove_dir/glove.6B.200d.txt

word_vec_size: 200
layers: 3
bridge: True

optim: adam
learning_rate: 0.001

single_pass: True

report_every: 100
log_file: runs/log.txt
tensorboard: True
tensorboard_log_dir: runs/first

