l1: fr
l2: en
seed: 330

batch_size: &batch_size 16
minlen: &minlen 3
maxlen: &maxlen 50

log_frequency: 100
val_frequency: 10000
checkpoint_frequency: 10000

n_valid: 10000
n_train_steps: 150000
n_valid_steps: 1000
do_full_eval: False

shared_encoder: False
m_bert: True

adam:
    lr: 0.0001
    weight_decay: 0.01

rmsp:
    lr: 0.00005
    weight_decay: 0.00

regularization: &regularization
    type:
        -

d_model: &d_model 768

encoder: bert
encoder_kwargs:
    fairseq: # overwrite fairseq base architecture
        encoder_embed_dim: *d_model
    bert:


decoder: fairseq
decoder_kwargs:
    fairseq: # overwrite fairseq base architecture
        encoder_embed_dim: *d_model
        decoder_embed_dim: *d_model
        decoder_ffn_embed_dim: 2048
        max_target_positions: *maxlen
        share_decoder_input_output_embed: True

discriminator_kwargs:
    << : *regularization
    maxlen: *maxlen
    d_model: *d_model
    output_dim: 1
