l1: multi
l2: multi
seed: 330

batch_size: &batch_size 32
minlen: &minlen 3
maxlen: &maxlen 50

log_frequency: 100
val_frequency: 1000
checkpoint_frequency: 50000

n_valid: 10000
n_train_steps: 2000
n_valid_steps: 100
do_full_eval: False

adam:
    lr: 0.00015

regularization: &regularization
    type:
        - hidden
    n_affine: 0

d_model: &d_model 768

encoder: bert
encoder_kwargs:
    fairseq: # overwrite fairseq base architecture
        encoder_embed_dim: *d_model
    bert:
        

decoder: fairseq
decoder_kwargs:
    fairseq: # overwrite fairseq base architecture
        encoder_embed_dim: *d_model
        decoder_embed_dim: *d_model
        decoder_ffn_embed_dim: 2048
        max_target_positions: *maxlen
        share_decoder_input_output_embed: True
        
discriminator_kwargs:
    << : *regularization
    maxlen: *maxlen
    d_model: *d_model
    output_dim: 1
